export type ColorVariant =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'dark'
  | 'light'
  | 'info'

export type ButtonVariant =
  | 'light'
  | 'dark'
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'link'
  | 'outline-primary'
  | 'outline-secondary'
  | 'outline-success'
  | 'outline-danger'
  | 'outline-warning'
  | 'outline-info'
  | 'outline-dark'
  | 'outline-light'

export type ButtonType =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'dark'
  | 'light'
  | 'link'
  | 'outline-primary'
  | 'outline-secondary'
  | 'outline-success'
  | 'outline-danger'
  | 'outline-warning'
  | 'outline-info'
  | 'outline-dark'
  | 'outline-light'

export type IconType =
  | 'add'
  | 'admin'
  | 'appointment'
  | 'appointment-add'
  | 'appointment-remove'
  | 'billing'
  | 'calendar'
  | 'dashboard'
  | 'down-arrow'
  | 'edit'
  | 'image'
  | 'incident'
  | 'inventory'
  | 'lab'
  | 'left-arrow'
  | 'logout'
  | 'medication'
  | 'menu'
  | 'patient'
  | 'patient-add'
  | 'patient-remove'
  | 'patients'
  | 'remove'
  | 'right-arrow'
  | 'save'
  | 'setting'
  | 'up-arrow'

export type SpinnerType =
  | 'BarLoader'
  | 'BeatLoader'
  | 'BounceLoader'
  | 'ClimbingBoxLoader'
  | 'ClipLoader'
  | 'DotLoader'
  | 'FadeLoader'
  | 'PulseLoader'
  | 'RotateLoader'
  | 'ScaleLoader'
  | 'SyncLoader'

export type SpinnerSizeUnit = 'px' | '%' | 'em'

