global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: lahim
    environment: development

scrape_configs:
  - job_name: lahim-server
    static_configs:
      - targets: ["lahim-server:3000"]
        labels:
          service: lahim-server
          instance: lahim-server-1
